### ISSUE TITLE
Connectivity to pf4j plugins

### ISSUE THREAD

**Issue by shubhamtyagi15** [spinnaker-plugin-examples/pf4jStagePlugin#402]
We're trying to integrate the p4fj plugins to our spinnaker project. There we're trying to use the sample plugin code. We don't have access to public GitHub in our organisation and the GitHub with domain url we're using requires authentication and thus can't be accessed properly from spinnaker pods. 
We've also tried with some workarounds such as writing controllers in same kube namespace and accessing the json and plugin zip files from there and were successful while trying to read the json file, but the zip file is not getting downloaded properly with that.
Here is our configurations from hal config file:

```
spinnaker:
    extensibility:
      plugins:
        Armory.RandomWaitPlugin:
          id: Armory.RandomWaitPlugin
          enabled: true
          version: 1.1.17
          extensions:
            armory.randomWaitStage:
              id: armory.randomWaitStage
              enabled: true
              config:
                defaultMaxWaitTime: 60
      repositories:
        spinnaker-plugin-examples:
          id: spinnaker-plugin-examples
          url: https://<service-url>/plugins.json

```
Can you please suggest if there is any workaround that we can use to avoid using GitHub for downloading the plugin zip files?
